### ISSUE TITLE
SSR + waitFor functionality

### ISSUE THREAD

**Issue by dasaeve** [TinkoffCreditSystems/stapp#20]
There are some problems with SSR right now

1) When waitFor was added in any module, whenReady promise waits this event and never resolves after it

2) It'll be great to have some kind of timeout settings for waitFor to resolve SSR if some events was never dispatched by apps. For example
```waitFor[  { event: someEventCreator, timeout: 1000 }  ]```

3) In current version whenReady resolves with full initial states of any modules. It'll be great for page size to exclude any empty reducers from final store.
For example this
``` app: { loaders: {}, someUsefulReducer: [1, 2, 3] } ```
turns into this
``` app: { someUsefulReducer: [1, 2, 3] } ```

**Comment by dmitry-korolev** [comment]
The first issue has to be investigated.
The second one, I agree, that would be useful.
As for the third proposal, I think, it would be nice to exclude untouched reducers (not empty).

Mechanism of connecting modules to the store will be completely rewritten in 2.0.0, and I'll try to take these issues into consideration.
