### ISSUE TITLE
Validate module breaks plain object errors

### ISSUE THREAD

**Issue by dasaeve** [TinkoffCreditSystems/stapp#24]
To handle some cases we want to extend error with flags. But validate module turn this rules
```
validate({
    rules: {
         'someField': value => { error: 'Error message', flag: true }
    }
})
```
into state without field name key
```
errors: {
    error: 'Error message'
}
```

**Comment by dmitry-korolev** [comment]
This behavior is intended as it allows setting several errors at once. 
Still, you may return any value:

```
const rule = (value, fieldName, state) => ({
	[fieldName]: {
		message: 'my message',
		flag: true
	}
})
```

Unfortunately, there is no other way to set several errors at once, which means that we cannot change this behavior currently.

If the suggested solution seems too verbose to you, you can create some wrapper. E.g., for sync validation:
```
const wrapWithObject = (result) => (value, fieldName, state) => {
	const result = rule(value, fieldName, state)
	return {
		[fieldName]: result
	}
}

const rule = wrapWithObject((value) => ({
	message: 'my message',
	flag: true
}))
```
