### ISSUE TITLE
Form react helper wouldn't update inner components

### ISSUE THREAD

**Issue by evgeniedasaev** [TinkoffCreditSystems/stapp#26]
**Problem**
For rendering some content based on upper component props we can't use components wrapped in Form helper.
For example:
```
const Form = createForm(app);

const SomeStatelessComponent = ({ fields }) => <Form>
{
   ({ handleSubmit }) => <form onSubmit={handleSubmit}>
         {   fields.map(renderField)   }

         <button onClick={handleSubmit}>OK</button>
    </form>
}
```

If fields was updated ```fields.map(renderField)``` wouldn't be called. But if something included in ```formSelector``` was changed form would be re-rendered.

**Solution**
Add "extra" selector which extends ```formSelector```
Mb something else

**Comment by dmitry-korolev** [comment]
Confirmed
https://codesandbox.io/s/w29v1kvxj7

Will be fixed in 2.0.0 release.

**Comment by dmitry-korolev** [comment]
Actually, are we sure that this should be fixed?

**Comment by dmitry-korolev** [comment]
@evgeniedasaev @berezinmv ^

**Comment by dmitry-korolev** [comment]
Irrelevant since 2.3.0.
We introduced other problems though 😆
