### ISSUE TITLE
Form async validation live page is broken

### ISSUE THREAD

**Issue by vkhv** [TinkoffCreditSystems/stapp#31]
If we try follow to link from
https://github.com/TinkoffCreditSystems/stapp/tree/master/examples/form-async-validation

to [codesandbox.io](https://codesandbox.io/s/github/TinkoffCreditSystems/stapp/tree/master/examples/form-async-validation)

We unfortunately see this:
![screen shot 2018-07-19 at 12 56 42](https://user-images.githubusercontent.com/6794386/42936026-c2c7052a-8b53-11e8-8f0d-dae1691fdd66.png)

**Comment by dmitry-korolev** [comment]
Hi, @vkhv.
Thanks for the report! Fortunately, this is already fixed in #21. We plan to merge it (and release Stapp 2.0.0, btw) tomorrow.
